# SecAI Framework
# The Security Framework for AI-Accelerated Development
# GitHub Pages configuration for Jekyll

# Site settings
title: "SecAI Framework"
description: "The Security Framework for AI-Accelerated Development: Enterprise-grade security for Cursor IDE with Azure AI Foundry integration"
baseurl: "" # Leave empty for root-level GitHub Pages
url: "https://zimaxnet.github.io" # GitHub Pages URL

# Author/Organization
author:
  name: "Security Research Team"
  corporation: "Your Limited Corporation"
  email: "research@yourcompany.com"

# Theme configuration
# Using just-the-docs theme for technical documentation
theme: just-the-docs
# For GitHub Pages, use remote theme instead:
remote_theme: just-the-docs/just-the-docs@v0.8.2

# Color scheme
color_scheme: cursor-research

# Logo and branding
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Heading anchor links
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2025 Your Limited Corporation. Distributed under <a href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY 4.0 License</a>."

# Footer "Edit this page" link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/zimaxnet/secai-framework"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

# Social links
aux_links:
  "View on GitHub":
    - "https://github.com/zimaxnet/secai-framework"
  "Research Blog":
    - "https://yourblog.com" # Update with your blog/social media

# Navigation structure
nav_enabled: true
nav_sort: case_insensitive

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Code syntax highlighting
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Mermaid diagram support
mermaid:
  version: "10.6.1"

# Collections
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# SEO settings
lang: en-US
twitter:
  username: yourtwitter # Update with your Twitter
  card: summary_large_image

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Callouts configuration
callouts_level: quiet
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: yellow
  tip:
    title: Tip
    color: green
  security:
    title: Security
    color: purple

# Enable copy code button
enable_copy_code_button: true

# Last modified date
last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y"

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

